"""add_reviews_table

Revision ID: 09d28b1818f6
Revises: 0011_renewal_reminder
Create Date: 2026-08-11 12:15:25.712041
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09d28b1818f6'
down_revision: Union[str, None] = '0011_renewal_reminder'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('features_key_key'), 'features', type_='unique')
    op.drop_index(op.f('ix_features_key'), table_name='features')
    op.create_index(op.f('ix_features_key'), 'features', ['key'], unique=True)
    op.drop_constraint(op.f('plan_features_plan_id_feature_id_key'), 'plan_features', type_='unique')
    op.create_unique_constraint('uq_plan_features_plan_feature', 'plan_features', ['plan_id', 'feature_id'])
    op.drop_index(op.f('ux_subscription_history_payment'), table_name='subscription_history', postgresql_where='(payment_id IS NOT NULL)')
    op.drop_index(op.f('ix_subscriptions_pending_downgrade'), table_name='subscriptions', postgresql_where="((status = 'ativa'::subscription_status) AND (pending_plan_id IS NOT NULL) AND (pending_plan_effective_at IS NOT NULL))")
    op.drop_index(op.f('ux_subscriptions_one_active_per_user'), table_name='subscriptions', postgresql_where="(status = 'ativa'::subscription_status)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ux_subscriptions_one_active_per_user'), 'subscriptions', ['user_id'], unique=True, postgresql_where="(status = 'ativa'::subscription_status)")
    op.create_index(op.f('ix_subscriptions_pending_downgrade'), 'subscriptions', ['status', 'pending_plan_id', 'pending_plan_effective_at'], unique=False, postgresql_where="((status = 'ativa'::subscription_status) AND (pending_plan_id IS NOT NULL) AND (pending_plan_effective_at IS NOT NULL))")
    op.create_index(op.f('ux_subscription_history_payment'), 'subscription_history', ['subscription_id', 'payment_id'], unique=True, postgresql_where='(payment_id IS NOT NULL)')
    op.drop_constraint('uq_plan_features_plan_feature', 'plan_features', type_='unique')
    op.create_unique_constraint(op.f('plan_features_plan_id_feature_id_key'), 'plan_features', ['plan_id', 'feature_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_features_key'), table_name='features')
    op.create_index(op.f('ix_features_key'), 'features', ['key'], unique=False)
    op.create_unique_constraint(op.f('features_key_key'), 'features', ['key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
