"""add_exam_papers_tables

Revision ID: b62d319494dd
Revises: 0013_create_reviews_table
Create Date: 2026-08-11 12:42:21.273307
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b62d319494dd'
down_revision: Union[str, None] = '0013_create_reviews_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_reviews_due_date'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_priority'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_question_id'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_status'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_user_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pendente', 'em_andamento', 'concluida', 'pular', name='review_status'), server_default=sa.text("'pendente'::review_status"), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('alta', 'media', 'baixa', name='review_priority'), server_default=sa.text("'media'::review_priority"), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('consecutive_correct', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('interval_days', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('reviews_question_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reviews_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey'))
    )
    op.create_index(op.f('idx_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('idx_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('idx_reviews_question_id'), 'reviews', ['question_id'], unique=False)
    op.create_index(op.f('idx_reviews_priority'), 'reviews', ['priority'], unique=False)
    op.create_index(op.f('idx_reviews_due_date'), 'reviews', ['due_date'], unique=False)
    # ### end Alembic commands ###
