"""add_reviews_table

Revision ID: c042a28b40ea
Revises: 09d28b1818f6
Create Date: 2026-08-11 12:22:25.844951
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c042a28b40ea'
down_revision: Union[str, None] = '09d28b1818f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
